{{- if .Values.integrations.s3.enabled | eq false }}
{{- if empty .Values.dependencies.s3.persistence.existingClaim }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{include "swanlab.s3.pvcName" .}}
  labels:
  {{- include "swanlab.s3.labels" . | nindent 4 }}
  {{- if .Values.dependencies.s3.customAnnotations }}
  annotations:
  {{- toYaml .Values.dependencies.s3.customAnnotations | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.dependencies.s3.persistence.storageSize | quote }}
    {{- if .Values.dependencies.s3.persistence.storageClass }}
  storageClassName: {{ .Values.dependencies.s3.persistence.storageClass | quote }}
{{- end }}
{{- end }}
{{- end }}