{{- if .Values.integrations.redis.enabled | eq false }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "swanlab.redis.fullname" . }}
  labels:
  {{- include "swanlab.redis.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
    {{- include "swanlab.redis.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
      {{- include "swanlab.redis.labels" . | nindent 8 }}
      {{- include "swanlab.redis.selectorLabels" . | nindent 8 }}
      {{- if .Values.dependencies.redis.customAnnotations }}
      annotations:
      {{- toYaml .Values.dependencies.redis.customAnnotations | nindent 8 }}
      {{- end }}
    spec:
      restartPolicy: Always
      imagePullSecrets:
      {{- include "swanlab.imagePullSecrets" . | nindent 8 }}
      containers:
      - name: redis
        image: "{{ .Values.dependencies.redis.image.repository }}:{{ .Values.dependencies.redis.image.tag }}"
        imagePullPolicy: {{ .Values.dependencies.redis.image.pullPolicy }}
        ports:
          - containerPort: {{ include "swanlab.redis.port" . }}
            name: redis
        volumeMounts:
          - mountPath: /data
            name: {{ include "swanlab.redis.fullname" . }}-volume
        {{- if .Values.dependencies.redis.resources }}
        resources:
        {{- toYaml .Values.dependencies.redis.resources | nindent 12 }}
        {{- end }}
      volumes:
        - name: {{ include "swanlab.redis.fullname" . }}-volume
          persistentVolumeClaim:
            claimName: {{ include "swanlab.redis.pvcName" . }}
      {{- if .Values.dependencies.redis.customNodeSelector }}
      nodeSelector:
      {{- toYaml .Values.dependencies.redis.customNodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.dependencies.redis.customTolerations }}
      tolerations:
      {{- toYaml .Values.dependencies.redis.customTolerations | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "swanlab.redis.fullname" . }}
  labels:
  {{- include "swanlab.redis.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
  {{- include "swanlab.redis.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ include "swanlab.redis.port" . }}
      name: redis
{{- end }}