apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "swanlab.house.fullname" . }}
  labels:
  {{- include "swanlab.house.labels" . | nindent 4 }}

spec:
  volumeClaimTemplates:
    - metadata:
        name: house
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: {{.Values.service.house.persistence.storageClass}}
        resources:
          requests:
            storage: {{.Values.service.house.persistence.storageSize}}
  replicas: {{ default 1 .Values.service.house.replicaCount }}
  selector:
    matchLabels:
    {{- include "swanlab.house.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "swanlab.house.labels" . | nindent 8 }}
      {{- include "swanlab.house.selectorLabels" . | nindent 8 }}
      {{- if .Values.service.house.customAnnotations }}
      annotations:
      {{- toYaml .Values.service.house.customAnnotations | nindent 8 }}
      {{- end }}
    spec:
      restartPolicy: Always
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: house
          image: {{ include "swanlab.house.image" . | quote }}
          imagePullPolicy: {{ .Values.service.house.image.pullPolicy }}
          ports:
            - containerPort: 3000
              name: house
          volumeMounts:
            - name: house
              mountPath: /data
          env:
            - name: SH_API_PREFIX
              value: "/api/house"
            - name: SH_LOG_PATH
              value: "/data/metrics/metrics.log"
            - name: SH_SERVER_URL
              value: "http://{{ include "swanlab.server.fullname" . }}:{{ include "swanlab.server.port" . }}/api"
            - name: SH_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "swanlab.clickhouse.secretName" . }}
                  key: username
            - name: SH_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "swanlab.clickhouse.secretName" . }}
                  key: password
            - name: SH_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ include "swanlab.clickhouse.secretName" . }}
                  key: host
            - name: SH_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ include "swanlab.clickhouse.secretName" . }}
                  key: tcpPort
            - name: SH_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "swanlab.clickhouse.secretName" . }}
                  key: database
            - name: MINIO_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: {{ include "swanlab.s3.secretName" .}}
                  key: endpoint
            - name: MINIO_SECRET_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "swanlab.s3.secretName" .}}
                  key: accessKey
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "swanlab.s3.secretName" .}}
                  key: secretKey
            - name: SH_DISTRIBUTED_ENABLE
              value: "true"
            - name: SH_REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "swanlab.redis.secretName" . }}
                  key: url
        - name: logrotate
          image: {{ .Values.service.house.logImage.repository }}:{{ .Values.service.house.logImage.tag }}
          env:
            - name: LOGS_DIRECTORIES
              value: "/data/metrics"
            - name: LOGROTATE_COPIES
              value: "25"
            - name: LOGROTATE_SIZE
              value: "25M"
            - name: LOGROTATE_CRONSCHEDULE
              value: "*/20 * * * * *"
            - name: LOGROTATE_INTERVAL
              value: "daily"
          volumeMounts:
            - name: house
              mountPath: /data
        - name: fluent-bit
          image: {{ .Values.service.house.fbImage.repository }}:{{ .Values.service.house.fbImage.tag }}
          command: [ "fluent-bit/bin/fluent-bit", "-c", "/conf/fluent-bit.conf" ]
          env:
            - name: LOG_PATH
              value: "/data/metrics/*.log"
            - name: CLICKHOUSE_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ include "swanlab.clickhouse.secretName" . }}
                  key: host
            - name: CLICKHOUSE_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ include "swanlab.clickhouse.secretName" . }}
                  key: httpPort
            - name: CLICKHOUSE_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "swanlab.clickhouse.secretName" . }}
                  key: username
            - name: CLICKHOUSE_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "swanlab.clickhouse.secretName" . }}
                  key: password
            - name: CLICKHOUSE_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ include "swanlab.clickhouse.secretName" . }}
                  key: database
          volumeMounts:
            - name: house
              mountPath: /data

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "swanlab.house.fullname" . }}
  labels:
  {{- include "swanlab.house.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
  {{- include "swanlab.house.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ include "swanlab.house.port" . }}
      targetPort: house