apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "swanlab.gateway.fullname" . }}
  labels:
  {{- include "swanlab.gateway.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
    {{- include "swanlab.gateway.selectorLabels" . | nindent 6 }}
  replicas: {{ default 1 .Values.gateway.replicas }}
  template:
    metadata:
      labels:
      {{- include "swanlab.gateway.labels" . | nindent 8 }}
      {{- include "swanlab.gateway.selectorLabels" . | nindent 8 }}
      {{- if .Values.gateway.customAnnotations }}
      annotations:
      {{- toYaml .Values.gateway.customAnnotations | nindent 8 }}
      {{- end }}
    spec:
      {{- include "swanlab.podAntiAffinity" (list .Values.global.podAntiAffinityPreset "swanlab.gateway.selectorLabels" . ) | nindent 6 }}
      initContainers:
        - name: download-identify
          image: "{{ .Values.gateway.identifyImage.repository }}:{{ .Values.gateway.identifyImage.tag }}"
          env:
            - name: COPY_TO
              # The download-identify script automatically creates the 'identify' folder in the /plugins-tmp directory.
              value: /plugins-tmp
          volumeMounts:
            - name: identify-plugin
              # Mount path for the shared volume
              mountPath: /plugins-tmp
      restartPolicy: Always
      imagePullSecrets:
      {{- include "swanlab.imagePullSecrets" . | nindent 8 }}
      containers:
        - name: traefik
          image: "{{ .Values.gateway.image.repository }}:{{ .Values.gateway.image.tag }}"
          args:
            - "--configfile=/etc/traefik/traefik.yaml"
          ports:
            - name: web
              containerPort: 80
            - name: metrics
              containerPort: 9100
            - name: traefik
              containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: "/etc/traefik/traefik.yaml"
              subPath: "traefik.yaml"
            - name: config
              mountPath: "/etc/traefik/dynamic/dynamic.yaml"
              subPath: "dynamic.yaml"
            - name: identify-plugin
              mountPath: /plugins-local/src/github.com/swanhubx/swanlab-helper
        {{- if .Values.gateway.resources }}
          resources:
        {{- toYaml .Values.gateway.resources | nindent 12 }}
        {{- end }}
      {{- if .Values.gateway.customNodeSelector }}
      nodeSelector:
      {{- toYaml .Values.gateway.customNodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.gateway.customTolerations }}
      tolerations:
      {{- toYaml .Values.gateway.customTolerations | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "swanlab.gateway.configmap" . }}
        - name: identify-plugin
          emptyDir: { }
---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "swanlab.gateway.fullname" . }}
  labels:
  {{- include "swanlab.gateway.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
  {{- include "swanlab.gateway.selectorLabels" . | nindent 4 }}
  ports:
    - port: 80
      name: web
