{{- if .Values.integrations.clickhouse.enabled | eq false }}
  {{- $username := .Values.dependencies.clickhouse.username | default "swanlab"}}
  {{- $password := .Values.dependencies.clickhouse.password | default "swanlab-clickhouse"}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "swanlab.clickhouse.secretName" . }}
  labels:
  {{- include "swanlab.clickhouse.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ $username | b64enc | quote }}
  password: {{ $password| b64enc | quote }}
{{- end }}