{{- if .Values.integrations.clickhouse.enabled }}
  {{- $_ := required "You must provide a value for .Values.integrations.clickhouse.existingSecret when .Values.integrations.clickhouse.enabled is true" .Values.integrations.clickhouse.existingSecret }}
{{- else }}
  {{- $database := "app"}}
  {{- $username := .Values.dependencies.clickhouse.username | default "swanlab"}}
  {{- $password := .Values.dependencies.clickhouse.password | default "swanlab-clickhouse"}}
  {{- $host := include "swanlab.clickhouse.fullname" . }}
  {{- $httpPort := "8123" }}
  {{- $tcpPort := "9000" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "swanlab.clickhouse.secretName" . }}
  labels:
  {{- include "swanlab.clickhouse.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ $username | b64enc | quote }}
  password: {{ $password| b64enc | quote }}
  database: {{ $database | b64enc | quote }}
  host: {{ $host | b64enc | quote }}
  httpPort: {{ $httpPort | b64enc | quote }}
  tcpPort: {{ $tcpPort | b64enc | quote }}
{{- end }}