{{- if .Values.integrations.postgres.enabled | eq false }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "swanlab.postgres.fullname" . }}
  labels:
  {{- include "swanlab.postgres.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
    {{- include "swanlab.postgres.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
      {{- include "swanlab.postgres.labels" . | nindent 8 }}
      {{- include "swanlab.postgres.selectorLabels" . | nindent 8 }}
      {{- if .Values.dependencies.postgres.customAnnotations }}
      annotations:
      {{- toYaml .Values.dependencies.postgres.customAnnotations | nindent 8 }}
      {{- end }}
    spec:
      restartPolicy: Always
      imagePullSecrets:
      {{- include "swanlab.imagePullSecrets" . | nindent 8 }}
      # 部分存储类创建的卷权限不是 postgres 用户可写，使用 initContainer 修正权限
      # 实测部分存储、k8s版本下单纯设置 fsGroup 无效，需要用 initContainer 修改目录属主
      securityContext:
        fsGroup: 999
      initContainers:
        - name: init-postgres-fs
          image: {{.Values.helper.repository}}:{{.Values.helper.tag}}
          command:
            - "sh"
            - "-c"
            - "mkdir -p /var/lib/postgresql/data && chmod 700 /var/lib/postgresql/data && chown -R 999:999 /var/lib/postgresql/data"
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: {{ include "swanlab.postgres.fullname" . }}-volume
              mountPath: /var/lib/postgresql
      containers:
      - name: postgres
        image: "{{ .Values.dependencies.postgres.image.repository }}:{{ .Values.dependencies.postgres.image.tag }}"
        imagePullPolicy: {{ .Values.dependencies.postgres.image.pullPolicy }}
        ports:
          - containerPort: {{ include "swanlab.postgres.port" . }}
            name: postgres
        env:
          - name: TZ
            value: "UTC"
          - name: PGDATA
            value: /var/lib/postgresql/data
          - name: POSTGRES_DB
            value: {{ include "swanlab.postgres.database" . }}
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: {{ include "swanlab.postgres.secretName" . }}
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "swanlab.postgres.secretName" . }}
                key: password
        volumeMounts:
          # 不要直接挂载到 /var/lib/postgresql/data ，因为存在 lost+found 目录会导致 postgres 启动失败
          # 挂载到父目录，Postgres 会在其中创建 data 子目录
          - mountPath: /var/lib/postgresql
            name: {{ include "swanlab.postgres.fullname" . }}-volume
        {{- if .Values.dependencies.postgres.resources }}
        resources:
        {{- toYaml .Values.dependencies.postgres.resources | nindent 12 }}
        {{- end }}
      volumes:
        - name: {{ include "swanlab.postgres.fullname" . }}-volume
          persistentVolumeClaim:
            claimName: {{ include "swanlab.postgres.pvcName" . }}
      {{- if .Values.dependencies.postgres.customNodeSelector }}
      nodeSelector:
      {{- toYaml .Values.dependencies.postgres.customNodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.dependencies.postgres.customTolerations }}
      tolerations:
      {{- toYaml .Values.dependencies.postgres.customTolerations | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "swanlab.postgres.fullname" . }}
  labels:
  {{- include "swanlab.postgres.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
  {{- include "swanlab.postgres.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ include "swanlab.postgres.port" . }}
      name: postgres
{{- end }}