name: 'Helm Chart Release'

on:
  push:
    branches:
      - main

# å…è®¸åŒæ—¶è¿è¡Œä¸€ä¸ªä½œä¸šï¼Œå¹¶å–æ¶ˆæ—§çš„ä½œä¸š
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checkout
        uses: actions/checkout@v4
        with:
          # å¿…é¡»è·å–å®Œæ•´çš„ Git å†å²ï¼Œä»¥ä¾¿ chart-releaser èƒ½å¤Ÿç”Ÿæˆæ­£ç¡®çš„ index æ–‡ä»¶
          fetch-depth: 0

      - name: ğŸ› ï¸ Set Git User
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: ğŸ› ï¸ Set up Helm
        # helm v3.18+
        uses: azure/setup-helm@v4.3.0

      - name: ğŸ“¥ Add Traefik Helm Repo
        run: |
          helm repo add traefik https://helm.traefik.io/traefik
          helm repo update

      - name: ğŸ¦¢ Add SwanLab Helm Repo
        run: |
          helm repo add swanlab https://helm.swanlab.cn
          helm repo update

      - name: ğŸ” Run Helm Lint
        run: |
          find ./charts -maxdepth 1 -mindepth 1 -type d | while read chart_dir; do
            echo "Linting $chart_dir..."
            helm dependency update "$chart_dir"
            helm lint "$chart_dir"
          done

#      - name: ğŸ‘® Move LICENSE to Chart Directories
#        run: |
#          find ./charts -maxdepth 1 -mindepth 1 -type d | while read chart_dir; do
#            echo "Copying LICENSE to $chart_dir..."
#            cp LICENSE "$chart_dir/"
#          done

      - name: ğŸš€ Release Helm Chart
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: ./charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
